version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_app_development
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge